language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux
  - osx 

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip3 install cpalgorithm

# command to run tests
script:
  - py.test tests/test.py 
