language: python

nguage: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.4
        - os: linux
          sudo: required
          python: 3.5
        - os: linux
          sudo: required
          python: 3.6
        - os: osx
          language: generic
          env: TOXENV=py34
        - os: osx
          language: generic
          env: TOXENV=py35
        - os: osx
          language: generic
          env: TOXENV=py36

# command to install dependencies
install:
  - pip install cpalgorithm

# command to run tests
script:
  - py.test tests/test.py 
