language: python

nguage: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.4
        - os: linux
          sudo: required
          python: 3.5
        - os: linux
          sudo: required
          python: 3.6
        - os: osx
          language: generic
          env: PIP=pip3
        - os: osx
          language: generic
          env: PIP=pip3
        - os: osx
          language: generic
          env: PIP=pip3

install: 
   - python3 -m pip install cpalgorithm

# command to run tests
script:
  - python3 tests/test.py 
