language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip3 install --index-url https://test.pypi.org/simple/ kmalgorithm

# command to run tests
script:
  - py.test test.py 
